### ISSUE TITLE
Add support for localetype de (German)

### ISSUE THREAD

**Issue by andreagr** [Realank/flutter_datetime_picker#32]
There is currently no support for German (de)

**Comment by Realank** [comment]
Yes, I don't know how to translate into German. People who are good at German are very welcome to submit a PR.

**Comment by angel1st** [comment]
@Realank - wouldn't be possible the package to utilize [dart/intl package](https://pub.dartlang.org/packages/intl), thus releasing itself from the burden of localization? I believe **dart/intl** supports wide variety of languages which can be used out of the box. What do you think?

**Comment by thorbenPollack** [comment]
I submitted a PR #36. :)

**Comment by Realank** [comment]
thanks for your advise @andreagr , dart/intl package seem to use internet connection to fetch translations, and I think it's not a good idea for our package, because intl package don't know what the date time format is for specific country, and if some apps don't support internet connection, it will cause error.

@thorbenPollack I've merged
